export const SibarButtons = [
  {
    key: "sidebar_genres",
    name: "Жанры",
    tabs: [
      "Action",
      "Adventure",
      "Comedy",
      "Drama",
      "Ecchi",
      "Fantasy",
      "Hentai",
      "Horror",
      "Mahou Shoujo",
      "Mecha",
      "Music",
      "Mystery",
      "Psychological",
      "Romance",
      "Sci-Fi",
      "Slice of Life",
      "Sports",
      "Supernatural",
      "Thriller",
    ],
  },
  {
    key: "sidebar_status",
    name: "Статус",
    tabs: [
      "Action",
      "Adventure",
      "Comedy",
      "Drama",
      "Ecchi",
      "Fantasy",
      "Hentai",
      "Horror",
      "Mahou Shoujo",
      "Mecha",
      "Music",
      "Mystery",
      "Psychological",
      "Romance",
      "Sci-Fi",
      "Slice of Life",
      "Sports",
      "Supernatural",
      "Thriller",
    ],
  },
  {
    key: "sidebar_type",
    name: "Тип",
    tabs: [
      "Action",
      "Adventure",
      "Comedy",
      "Drama",
      "Ecchi",
      "Fantasy",
      "Hentai",
      "Horror",
      "Mahou Shoujo",
      "Mecha",
      "Music",
      "Mystery",
      "Psychological",
      "Romance",
      "Sci-Fi",
      "Slice of Life",
      "Sports",
      "Supernatural",
      "Thriller",
    ],
  },
  {
    key: "sidebar_kek",
    name: "Kek",
    tabs: [
      "Action",
      "Adventure",
      "Comedy",
      "Drama",
      "Ecchi",
      "Fantasy",
      "Hentai",
      "Horror",
      "Mahou Shoujo",
      "Mecha",
      "Music",
      "Mystery",
      "Psychological",
      "Romance",
      "Sci-Fi",
      "Slice of Life",
      "Sports",
      "Supernatural",
      "Thriller",
    ],
  },
];
export const MeryGoLife = [
  {
    key: "mery_go_life_1",
  },
  {
    key: "mery_go_life_2",
  },
  {
    key: "mery_go_life_3",
  },
  {
    key: "mery_go_life_4",
  },
  {
    key: "mery_go_life_5",
  },
  {
    key: "mery_go_life_6",
  },
  {
    key: "mery_go_life_7",
  },
  {
    key: "mery_go_life_8",
  },
  {
    key: "mery_go_life_9",
  },
  {
    key: "mery_go_life_10",
  },
  {
    key: "mery_go_life_11",
  },
];
